security:
    encoders:
        App\Entity\User: bcrypt

    role_hierarchy:
        ROLE_SELLER:      [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_SELLER]

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }
        user:
            entity:
                class: App\Entity\User
                property: email
        auth_token_user_provider:
            id: App\Security\AuthTokenUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api(?!/auth-tokens$)
            stateless: true
            simple_preauth:
                authenticator: App\Security\AuthTokenAuthenticator
            provider: auth_token_user_provider
            anonymous: ~
        main:
            provider: user
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: test


            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
